### PR TITLE
Implemented a minimal ob-restclient

### PR DESCRIPTION
**Pull request by alf**
This is a simple but working integration with org-mode

### CODE REVIEW

**Comment by pashky** [comment]
So, it works and no need to modify restclient.el then? Amazing. Emacs is so flexible!

I wonder though, as this is a PR, am I right that you want it distributed as part of restclient? 
Even if it depends on some internal restclient features (like restclient-within-call variable, which itself is a hack around url.el issues), I'd think that having it as a separately maintained package will be better. What do you think?

**Comment by alf** [comment]
Yes, I think it's natural to include it as part of restclient. 

Having ob-restclient.el makes no sense unless you have restclient.el. By having it bundled it will reach a much wider audience.

If you don't want to include it that's ok too. Just remember that by including it you can close your longest outstanding issue :)

I might improve the current implementation further to allow overriding what mode emacs should use for the result (in cases where the auto detection fails). If so I'll create a new pull request for that.

Beyond that change there really isn't much that needs to be maintained in the ob-restclient.el code.

**Comment by CarlQLange** [comment]
:+1: This would be amazing to have - ob-http has a couple of issues, and I already use restclient-mode :)

**Comment by eggcaker** [comment]
how about the variables? just tried the ob-restclient, if put some variables inside url. not working.

**Comment by alf** [comment]
I've created [ob-restclient.el](https://github.com/alf/ob-restclient.el) as a separate package and sent a pull request to get it into [melpa](https://github.com/milkypostman/melpa/pull/3366). Thus we can close this pull request.

Feature requests for the org-mode integration should be created [here](https://github.com/alf/ob-restclient.el/issues).

**Pull request closed without merging**
