### PR TITLE
added function and key binding to copy a request's curl command to the clipboard

### PR DESCRIPTION
**Pull request by timjstewart**
Hi, I really like restclient but yesterday someone asked me to send them a request I was making.  Since they did not use Emacs, I wanted to send them the curl command for the request but I'm lazy and I didn't want to build the curl command by hand.  

So I wrote another command for restclient that builds the curl command for you and copies it to the clipboard.

### CODE REVIEW

**Comment by timjstewart** [comment]
BTW, the C-c C-u key binding spells out the first two letters of curl.  Hopefully that makes it more memorable.

**Comment by localredhead** [comment]
+:100:  making restclient another level of awesome

**Comment by timjstewart** [comment]
Thanks!

**Comment by pashky** [comment]
Copy/pasting code is bad, didn't you know? :)
I've redone your code in a slightly shorter and cleaner way. Please update and check if it works for you.

**Comment by timjstewart** [comment]
Yes, I didn't want to go through the effort of a full refactoring if the PR
was going to be rejected.  Thanks for cleaning up the code.  It works for
me.  I have not tested it in environments that don't have a clipboard.

**Pull request closed without merging**
