### PR TITLE
Print curl command next to http response

### PR DESCRIPTION
**Pull request by ancane**
Hello, @pashky.

I've made small customizable feature, that prints curl command at the beginning of http response buffer,
so that it's possible to save it and share as complete rest call example with non-emacs person.

Thanks.

### CODE REVIEW

**Comment by pashky** [comment]
I'm not a big fan of putting it into response window, even if it's customizable. 

Could we make it a separate thing, like, simply convert current request you have cursor on and copy it into kill ring/clipboard/separate buffer if you press C-c C-l or something? This way, I won't need to decide once and forever if I want to have it in each response buffer or not, yet it will always be at hand when needed.
 
I guess it's time to abstract out `restclient-http-send-current` and pass a function as a parameter instead of hard coded restclient-http-do call. It's too many flags there already (I mean, `raw` and `stay-in-window`).

**Comment by ancane** [comment]
Good point. I'll try updating this PR if you don't mind.

**Comment by stardiviner** [comment]
@ancane Is it merged now? I have not found in latest git version.

**Comment by ancane** [comment]
Hi, stardiviner.
I guess it's not. If you need that, feature you may find it here:
https://github.com/ancane/restclient.el


2015-07-23 5:08 GMT+03:00 stardiviner <notifications@github.com>:

**Comment by stardiviner** [comment]
@ancane I see. Thanks.

**Pull request closed without merging**
