### PR TITLE
Automatically activate restclient mode with files ending with .rest

### PR DESCRIPTION
**Pull request by kootenpv**
Something I immediately added.

### CODE REVIEW

**Comment by arichiardi** [comment]
:+1:

**Comment by kootenpv** [comment]
No comment?

**Comment by pashky** [comment]
There's no value in this change. It's clearly known to anyone who's used emacs for at least 15 minutes how to assign modes to file names, and .rest is just another made up file extension that isn't used by anyone else.

**Comment by kootenpv** [comment]
It helps when the package maintainer suggests the standard though. And honestly, I'm sure there were people using your package without a mode hook, while if you would have the code here people would just copy and be happy with it.

**Comment by kidmose** [comment]
I've used emacs for more than 15 minutes, knew this could be done, didn't now exactly how => The change would certainly add value for me, but I'll just update it now. 

Thanks @kootenpv  :)

**Pull request closed without merging**
